version: '3'

services:
  traefik:
    build: dockerfiles/traefik/
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  logstash:
    build: ./dockerfiles/logstash
    environment:
      - ELASTIC_PASSWORD=MagicWord
      - XPACK_MONITORING_ENABLED=False
    ports:
      - "5044:5044"
      - "9400:9400"
      - "3232:3232"
    volumes:
      - "./dockerfiles/logstash/pipeline:/usr/share/logstash/pipeline/"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    ports:
      - "9200"
    environment:
      - ELASTIC_PASSWORD=MagicWord
      - discovery.type=single-node
    labels:
      - "traefik.enable=true"
      - "traefik.backend=elasticsearch"
      - "traefik.frontend.rule=Host:elasticsearch.traefik.doubting.org"

  cerebro:
    image: yannart/cerebro:0.6.5
    ports:
      - "9000"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=cerebro"
      - "traefik.frontend.rule=Host:cerebro.traefik.doubting.org"

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - "9090"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=prometheus"
      - "traefik.frontend.rule=Host:prometheus.traefik.doubting.org"


